(()=>{
'use strict';
const KEY='chars', MONEY='money', CURRENT='char';
const defs={scout:{name:'SCOUT',cost:0,tag:'Hızlı keşif',speed:92,armor:55,damage:70},assault:{name:'ASSAULT',cost:1500,tag:'Dengeli savaşçı',speed:78,armor:72,damage:84},tank:{name:'TANK',cost:3000,tag:'Ağır zırh',speed:58,armor:100,damage:92},elite:{name:'ELITE',cost:5000,tag:'Elit operasyon',speed:88,armor:82,damage:96}};
function read(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}}
function owned(){let a=read(KEY,['scout']);if(!Array.isArray(a))a=['scout'];if(!a.includes('scout'))a.unshift('scout');return a}
function setOwned(a){localStorage.setItem(KEY,JSON.stringify([...new Set(a)]))}
function getMoney(){const dom=Number(document.getElementById('money')?.textContent);if(Number.isFinite(dom)&&dom>0)return dom;const n=Number(localStorage.getItem(MONEY));return Number.isFinite(n)?n:0}
function setMoney(n){n=Math.max(0,Math.floor(n));localStorage.setItem(MONEY,String(n));for(const id of ['money','lbMoney']){const e=document.getElementById(id);if(e)e.textContent=n}window.dispatchEvent(new CustomEvent('fps:money',{detail:{money:n}}))}
const css=document.createElement('style');css.textContent=`#charShop{position:fixed;inset:0;z-index:140;background:#050a0ee8;display:none;align-items:center;justify-content:center;padding:20px;font-family:Arial}#charShop.show{display:flex}.csBox{width:min(760px,94vw);background:#101b24;border:1px solid #ffffff25;border-radius:16px;box-shadow:0 20px 70px #000b;padding:22px}.csHead{display:flex;align-items:center}.csHead h2{margin:0}.csClose{margin-left:auto;border:0;border-radius:8px;padding:9px 15px;background:#263846;color:#fff;font-weight:900}.csGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.csCard{border:1px solid #ffffff18;border-radius:12px;background:#ffffff08;padding:14px;text-align:center}.csCard.sel{border-color:#e5ad4f;box-shadow:0 0 0 1px #e5ad4f44 inset}.csIcon{font-size:45px;height:62px}.csCard h3{margin:5px 0}.csCard small{opacity:.65}.csCard button{width:100%;margin-top:12px;padding:10px;border:0;border-radius:7px;font-weight:900;background:#e5ad4f}.csCard button.owned{background:#2c9b63;color:#fff}.csCard button.lock{background:#394957;color:#fff}@media(max-width:700px){.csGrid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(css);
const ui=document.createElement('div');ui.id='charShop';ui.innerHTML=`<div class="csBox"><div class="csHead"><h2>🪖 OPERATÖR MERKEZİ</h2><span id="csMoney" style="margin-left:14px;color:#ffd66e;font-weight:900"></span><button class="csClose" id="csClose">KAPAT</button></div><div style="opacity:.65;margin-top:5px">Yeni operatörlerin kilidini aç ve savaş stilini değiştir.</div><div class="csGrid" id="csGrid"></div></div>`;document.body.appendChild(ui);
const icons={scout:'🪖',assault:'⚔️',tank:'🛡️',elite:'👑'};
function render(){const g=document.getElementById('csGrid'),own=owned(),cur=localStorage.getItem(CURRENT)||'scout';document.getElementById('csMoney').textContent='💰 '+getMoney();g.innerHTML='';Object.entries(defs).forEach(([id,c])=>{const ok=own.includes(id),sel=cur===id;const d=document.createElement('div');d.className='csCard'+(sel?' sel':'');d.innerHTML=`<div class="csIcon">${icons[id]}</div><h3>${c.name}</h3><small>${c.tag}<br>HIZ ${c.speed} • ZIRH ${c.armor} • HASAR ${c.damage}</small><button class="${ok?'owned':'lock'}">${sel?'SEÇİLİ':ok?'KULLAN':('₺'+c.cost+' AÇ')}</button>`;d.querySelector('button').onclick=()=>{if(ok){localStorage.setItem(CURRENT,id);window.dispatchEvent(new CustomEvent('fps:character',{detail:{id,...c,owned:true}}));render();return}const money=getMoney();if(money<c.cost){toast('💰 Yeterli paran yok');return}setMoney(money-c.cost);setOwned([...own,id]);localStorage.setItem(CURRENT,id);window.dispatchEvent(new CustomEvent('fps:character',{detail:{id,...c,owned:true,purchased:true}}));render();toast('✅ '+c.name+' açıldı!')};g.appendChild(d)})}
function toast(t){const e=document.createElement('div');e.textContent=t;e.style='position:fixed;z-index:160;left:50%;bottom:13%;transform:translateX(-50%);background:#101b24ee;border:1px solid #ffffff25;padding:12px 18px;border-radius:9px;font:900 15px Arial;box-shadow:0 8px 30px #0008';document.body.appendChild(e);setTimeout(()=>e.remove(),1500)}
window.__openCharacterShop=()=>{ui.classList.add('show');render()};document.getElementById('csClose').onclick=()=>ui.classList.remove('show');
function hookNav(){const buttons=[...document.querySelectorAll('.lbNav button')];const inv=buttons.find(b=>b.textContent.includes('ENVANTER'));if(inv&&!inv.dataset.charHook){inv.dataset.charHook='1';inv.onclick=()=>window.__openCharacterShop()}}
hookNav();new MutationObserver(hookNav).observe(document.body,{childList:true,subtree:true});
let reverting=false,lastOwned=localStorage.getItem(CURRENT)||'scout';
window.addEventListener('fps:character',e=>{const id=e.detail?.id;if(!id||reverting)return;const own=owned();if(!own.includes(id)){reverting=true;localStorage.setItem(CURRENT,lastOwned);const ids=Object.keys(defs),a=ids.indexOf(lastOwned),b=ids.indexOf(id),delta=(a-b+ids.length)%ids.length;const next=document.getElementById('charNext'),prev=document.getElementById('charPrev');if(delta<=ids.length/2){for(let i=0;i<delta;i++)prev?.click()}else{for(let i=0;i<ids.length-delta;i++)next?.click()}setTimeout(()=>{reverting=false;window.__openCharacterShop();toast('🔒 '+defs[id].name+' kilitli • Operatör Merkezinden aç')},60);return}lastOwned=id;localStorage.setItem(CURRENT,id)});
const oldSend=WebSocket.prototype.send;WebSocket.prototype.send=function(data){try{if(typeof data==='string'){const m=JSON.parse(data);if(m?.type==='state'){m.character=localStorage.getItem(CURRENT)||'scout';data=JSON.stringify(m)}}}catch{}return oldSend.call(this,data)};
window.fpsCharacterDefs=defs;window.fpsCharacterOwned=owned;
})();