(()=>{
const css=document.createElement('style');css.textContent=`#contentHub{position:fixed;inset:0;z-index:90;background:#071018f5;color:#fff;font-family:Arial;display:none;overflow:auto;padding:26px}#contentHub.show{display:block}.ch{max-width:1150px;margin:auto}.chHead{display:flex;align-items:center;gap:12px;margin-bottom:18px}.chHead h1{margin:0}.chClose{margin-left:auto;background:#d69a36;border:0;padding:10px 18px;border-radius:7px;font-weight:900}.tabs{display:flex;gap:8px;margin-bottom:15px;flex-wrap:wrap}.tabs button{padding:10px 18px;border:1px solid #ffffff22;background:#14222d;color:#fff;border-radius:7px;font-weight:800}.tabs button.on{background:#d69a36;color:#111}.contentGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.item{background:#101c25;border:1px solid #ffffff16;border-radius:10px;padding:14px;text-align:center}.item .preview{height:130px;border-radius:8px;margin-bottom:10px;display:flex;align-items:center;justify-content:center;background:linear-gradient(145deg,#243746,#0a1015);font-size:54px}.item h3{margin:6px 0}.item small{opacity:.65}.item button{margin-top:10px;width:100%;padding:9px;border:0;border-radius:6px;font-weight:900}.equip{background:#2d9d62;color:#fff}.buy{background:#d69a36;color:#111}.owned{background:#334552;color:#fff}.mapCard{grid-column:span 2;text-align:left}.mapPreview{height:180px!important;font-size:65px!important;background:radial-gradient(circle,#315a43,#13251b 55%,#09110d)!important}.mapCard button{background:#d69a36;color:#111}.selected{outline:2px solid #e4ad51}@media(max-width:800px){.contentGrid{grid-template-columns:1fr 1fr}.mapCard{grid-column:span 2}}`;document.head.appendChild(css);
const hub=document.createElement('div');hub.id='contentHub';hub.innerHTML=`<div class="ch"><div class="chHead"><h1>🎒 ARSENAL & KOLEKSİYON</h1><span id="chMoney" style="color:#ffd36b;font-weight:900">💰 0</span><button class="chClose" id="chClose">KAPAT</button></div><div class="tabs"><button class="on" data-tab="weapons">SİLAH SKİNLERİ</button><button data-tab="chars">KARAKTERLER</button><button data-tab="outfits">KOSTÜMLER</button><button data-tab="maps">HARİTALAR</button></div><div id="chGrid" class="contentGrid"></div></div>`;document.body.appendChild(hub);
const maps=[['🏙️','METRO CITY','Şehir / Yakın çatışma'],['🌲','BLACK FOREST','Orman / Orta mesafe'],['🏜️','DESERT OUTPOST','Çöl / Uzun mesafe'],['🏭','IRON FACTORY','Fabrika / Karma savaş']];
const skins=[['🔫','ONYX','Pistol'],['🟦','FROST','SMG'],['🟩','JUNGLE','AR-15'],['🟥','CRIMSON','Shotgun'],['⬛','SHADOW','Sniper'],['🟨','GOLD','LMG']];
const chars=[['🪖','SCOUT','Hızlı keşif'],['⚔️','ASSAULT','Dengeli savaşçı'],['🛡️','TANK','Yüksek zırh'],['👑','ELITE','Hız + dayanıklılık']];
const outfits=[['🥷','NIGHT OPS','Gizli operasyon'],['🪖','URBAN FORCE','Şehir kamuflajı'],['🌲','FOREST CAMO','Orman kamuflajı'],['🏜️','DESERT CAMO','Çöl kamuflajı'],['🔥','RED STRIKE','Özel kostüm'],['❄️','ARCTIC','Kış operasyonu']];
function money(){return Number(document.getElementById('money')?.textContent||localStorage.getItem('money')||0)}function render(tab){const g=document.getElementById('chGrid');g.innerHTML='';document.getElementById('chMoney').textContent='💰 '+money();let data=tab==='weapons'?skins:tab==='chars'?chars:tab==='outfits'?outfits:maps;data.forEach((x,i)=>{const card=document.createElement('div');card.className='item '+(tab==='maps'?'mapCard':'');card.innerHTML=`<div class="preview ${tab==='maps'?'mapPreview':''}">${x[0]}</div><h3>${x[1]}</h3><small>${x[2]}</small><button class="buy">${tab==='maps'?(i===0?'SEÇ':'KİLİTLİ'):i===0?'KULLAN':'₺'+([800,1200,1600,2200,3000,4200][i]||1500)}</button>`;g.appendChild(card);card.querySelector('button').onclick=()=>{if(tab==='maps'){if(i===0||confirm('Bu haritayı seçmek istiyor musun?')){localStorage.setItem('selectedMap',x[1]);document.querySelectorAll('.item').forEach(a=>a.classList.remove('selected'));card.classList.add('selected');window.dispatchEvent(new CustomEvent('fps:map',{detail:{name:x[1],index:i}}));}}else{card.classList.add('selected');window.dispatchEvent(new CustomEvent('fps:cosmetic',{detail:{type:tab,name:x[1],index:i}}));}}});}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('on'));b.classList.add('on');render(b.dataset.tab)});document.getElementById('chClose').onclick=()=>hub.classList.remove('show');window.addEventListener('fps:content',()=>{hub.classList.add('show');render('weapons')});window.__openContent=()=>hub.classList.add('show');
})();