(()=>{'use strict';
const STYLE=`#teamMatch{position:fixed;inset:0;z-index:140;background:radial-gradient(circle at 50% 35%,#19344acc,#05080ef5 65%);display:none;align-items:center;justify-content:center;font-family:Arial,sans-serif;color:#fff}#teamMatch.on{display:flex}.tm{width:min(1050px,94vw);padding:26px;border:1px solid #ffffff22;border-radius:22px;background:#07101bdd;box-shadow:0 25px 80px #000b}.tm h1{margin:0 0 6px;font-size:28px}.tmSub{color:#9fb0c8}.teams{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:22px 0}.team{padding:18px;border-radius:16px;background:#ffffff08;border:1px solid #ffffff15}.team.red{border-color:#ff445555}.team.blue{border-color:#4488ff55}.team h2{margin:0 0 14px}.slot{display:flex;justify-content:space-between;padding:10px;border-radius:9px;background:#ffffff08;margin:7px 0}.ready{color:#5cff9a}.tmBtns{display:flex;gap:10px;flex-wrap:wrap}.tmBtn{border:0;border-radius:10px;padding:12px 18px;background:#1b6cff;color:#fff;font-weight:800;cursor:pointer}.tmBtn.alt{background:#ffffff12}.tmCode{font-size:18px;font-weight:900;letter-spacing:4px;color:#ffd65c}.tmCount{font-size:58px;text-align:center;font-weight:900;display:none}.tmStatus{margin:12px 0;color:#a9b8ca}@media(max-width:700px){.teams{grid-template-columns:1fr}.tm{padding:16px}.tm h1{font-size:22px}}`;
const st=document.createElement('style');st.textContent=STYLE;document.head.appendChild(st);const root=document.createElement('div');root.id='teamMatch';root.innerHTML=`<div class="tm"><h1>⚔️ TAKIM SAVAŞI</h1><div class="tmSub">4v4 • Hızlı ve rekabetçi maç</div><div class="tmStatus" id="tmStatus">Sunucuya bağlanıyor...</div><div>ODA: <span class="tmCode" id="tmCode">------</span></div><div class="teams"><div class="team red"><h2>🔴 KIRMIZI <small id="redCount">0/4</small></h2><div id="redList"></div></div><div class="team blue"><h2>🔵 MAVİ <small id="blueCount">0/4</small></h2><div id="blueList"></div></div></div><div class="tmCount" id="tmCount"></div><div class="tmBtns"><button class="tmBtn" id="tmReady">HAZIR</button><button class="tmBtn" id="tmStart">MAÇI BAŞLAT</button><button class="tmBtn alt" id="tmLeave">AYRIL</button></div></div>`;document.body.appendChild(root);
let ws=null,myId=null,room=null,ready=false,players=new Map();
function send(o){if(ws?.readyState===1)ws.send(JSON.stringify(o))}function status(t){const e=document.getElementById('tmStatus');if(e)e.textContent=t}function render(){const r=[...players.values()].filter(p=>p.team==='red'),b=[...players.values()].filter(p=>p.team==='blue');document.getElementById('redCount').textContent=`${r.length}/4`;document.getElementById('blueCount').textContent=`${b.length}/4`;document.getElementById('redList').innerHTML=r.map(p=>`<div class="slot"><span>${p.name||'Oyuncu'}</span><b class="${p.ready?'ready':''}">${p.ready?'✓ HAZIR':'BEKLİYOR'}</b></div>`).join('')||'<div class="slot">Boş slot</div>';document.getElementById('blueList').innerHTML=b.map(p=>`<div class="slot"><span>${p.name||'Oyuncu'}</span><b class="${p.ready?'ready':''}">${p.ready?'✓ HAZIR':'BEKLİYOR'}</b></div>`).join('')||'<div class="slot">Boş slot</div>'}
function connect(){try{ws=new WebSocket('wss://fps-arena-server.onrender.com')}catch(e){status('Sunucu bağlantısı kurulamadı');return}ws.onopen=()=>{status('Sunucu bağlı • takım eşleşmesi hazır');send({type:'teamRoom',action:'quick',name:localStorage.getItem('playerName')||'Oyuncu',character:localStorage.getItem('char')||'scout'})};ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='teamWelcome'){myId=m.id;room=m.room;document.getElementById('tmCode').textContent=m.code||'------';players=new Map((m.players||[]).map(p=>[p.id,p]));render()}else if(m.type==='teamState'){room=m.room||room;players=new Map((m.players||[]).map(p=>[p.id,p]));render()}else if(m.type==='teamStart'){countdown(m.seconds||3)}else if(m.type==='teamError')status(m.message||'Oda hatası')} }
function countdown(n){const c=document.getElementById('tmCount');c.style.display='block';let x=n;c.textContent=x;const t=setInterval(()=>{x--;if(x<=0){clearInterval(t);c.textContent='GO!';setTimeout(()=>{root.classList.remove('on');window.dispatchEvent(new CustomEvent('fps:match-start',{detail:room}))},450)}else c.textContent=x},1000)}
window.openTeamMatch=()=>{root.classList.add('on');connect()};document.getElementById('tmReady').onclick=()=>{ready=!ready;send({type:'teamReady',ready});document.getElementById('tmReady').textContent=ready?'HAZIR ✓':'HAZIR'};document.getElementById('tmStart').onclick=()=>send({type:'teamStart'});document.getElementById('tmLeave').onclick=()=>{send({type:'teamLeave'});root.classList.remove('on');if(ws)ws.close()};
window.addEventListener('fps:team-match',window.openTeamMatch);
})();