(()=>{'use strict';
const W={pistol:{kick:.018,flash:.08,shake:.045},smg:{kick:.025,flash:.07,shake:.055},rifle:{kick:.035,flash:.1,shake:.065},shotgun:{kick:.08,flash:.14,shake:.12},sniper:{kick:.12,flash:.16,shake:.16},lmg:{kick:.03,flash:.11,shake:.07}};
let kick=0,flash=0,shake=0,reloadUntil=0,lastAmmo='';
const style=document.createElement('style');style.textContent='.fps-muzzle{position:fixed;left:50%;top:50%;width:22px;height:22px;transform:translate(-50%,-50%);border-radius:50%;background:radial-gradient(circle,#fff 0,#ffd45a 25%,#ff7b00 48%,transparent 70%);opacity:0;pointer-events:none;z-index:40}.fps-reload{position:fixed;left:50%;bottom:12%;transform:translateX(-50%);padding:7px 14px;border-radius:8px;background:#05080dcc;border:1px solid #ffffff44;font:700 13px Arial;opacity:0;z-index:40}.fps-hitflash{position:fixed;inset:0;border:3px solid #ff444466;opacity:0;pointer-events:none;z-index:39}';document.head.appendChild(style);
const muzzle=document.createElement('div');muzzle.className='fps-muzzle';document.body.appendChild(muzzle);const rel=document.createElement('div');rel.className='fps-reload';rel.textContent='↻ YENİDEN DOLDURULUYOR';document.body.appendChild(rel);const hit=document.createElement('div');hit.className='fps-hitflash';document.body.appendChild(hit);
function weapon(){return String(window.__fpsGame?.currentWeapon||document.getElementById('wep')?.textContent||'pistol').toLowerCase()}
function shoot(){const d=W[weapon()]||W.pistol;kick=Math.min(.18,kick+d.kick);shake=Math.min(.25,shake+d.shake);flash=d.flash;muzzle.style.opacity='1';setTimeout(()=>muzzle.style.opacity='0',45)}
function reload(){if(reloadUntil>Date.now())return;reloadUntil=Date.now()+850;rel.style.opacity='1';setTimeout(()=>rel.style.opacity='0',850)}
window.addEventListener('fps:shoot',shoot);window.addEventListener('fps:reload',reload);window.addEventListener('fps:remote-shot',()=>{flash=.04});window.addEventListener('fps:damage',()=>{hit.style.opacity='1';setTimeout(()=>hit.style.opacity='0',80)});
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')reload()});
function tick(){const c=document.querySelector('.cross');if(c){c.style.transform=`translate(-50%,-50%) translate(${(Math.random()-.5)*shake*22}px,${(Math.random()-.5)*shake*22}px) rotate(${(Math.random()-.5)*shake*18}deg)`;if(kick){c.style.fontSize=(26+kick*55)+'px';kick*=.72}else c.style.fontSize='26px'}shake*=.78;if(flash>0){muzzle.style.transform=`translate(-50%,-50%) scale(${1+flash*3})`;flash*=.7}else muzzle.style.transform='translate(-50%,-50%)';requestAnimationFrame(tick)}tick();
})();